package com.cyclopsgroup.levistone.torque;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Dec 23 10:04:47 CST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UserPeer
    extends com.cyclopsgroup.levistone.torque.BaseUserPeer
{
}
