insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2000, 'c_tnd_users', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2001, 'c_tnd_usrobjs', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2002, 'c_tnd_groups', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2003, 'c_tnd_grphrch', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2004, 'c_tnd_user_group', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2005, 'c_tnd_acls', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2006, 'c_tnd_roles', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2007, 'c_tnd_confs', 1000, 10);
insert into ID_TABLE (id_table_id, table_name, next_id, quantity) VALUES (2008, 'c_tnd_menus', 1000, 10);
