package com.cyclopsgroup.levistone.torque.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Dec 23 12:05:28 CST 2004]
  *
  */
public class AddressMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "com.cyclopsgroup.levistone.torque.map.AddressMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("default");

        dbMap.addTable("cg_levistone_address");
        TableMap tMap = dbMap.getTable("cg_levistone_address");

        tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);

        tMap.setPrimaryKeyMethodInfo(tMap.getName());

              tMap.addPrimaryKey("cg_levistone_address.ADDRESS_ID", new Long(0));
                    tMap.addColumn("cg_levistone_address.DETAILS1", new String());
                    tMap.addColumn("cg_levistone_address.DETAILS2", new String());
                    tMap.addColumn("cg_levistone_address.CITY", new String());
                    tMap.addColumn("cg_levistone_address.STATE", new String());
                    tMap.addColumn("cg_levistone_address.ZIP_CODE", new String());
                    tMap.addColumn("cg_levistone_address.COUNTRY", new String());
                    tMap.addForeignKey(
                "cg_levistone_address.USER_ID", new Long(0) , "cg_levistone_user" ,
                "user_id");
          }
}
