package com.cyclopsgroup.levistone.torque;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Dec 23 12:05:28 CST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to User
 */
public abstract class BaseUser extends BaseObject
{
    /** The Peer class */
    private static final UserPeer peer =
        new UserPeer();

        
    /** The value for the id field */
    private long id;
      
    /** The value for the userName field */
    private String userName;
      
    /** The value for the email field */
    private String email;
      
    /** The value for the birthday field */
    private Date birthday;
      
    /** The value for the description field */
    private String description;
  
    
    /**
     * Get the Id
     *
     * @return long
     */
    public long getId()
    {
        return id;
    }

                                              
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(long v) throws TorqueException
    {
    
                  if (this.id != v)
              {
            this.id = v;
            setModified(true);
        }
    
          
                                  
        // update associated Address
        if (collAddresss != null)
        {
            for (int i = 0; i < collAddresss.size(); i++)
            {
                ((Address) collAddresss.get(i))
                    .setUserId(v);
            }
        }
                      }
  
    /**
     * Get the UserName
     *
     * @return String
     */
    public String getUserName()
    {
        return userName;
    }

                        
    /**
     * Set the value of UserName
     *
     * @param v new value
     */
    public void setUserName(String v) 
    {
    
                  if (!ObjectUtils.equals(this.userName, v))
              {
            this.userName = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Email
     *
     * @return String
     */
    public String getEmail()
    {
        return email;
    }

                        
    /**
     * Set the value of Email
     *
     * @param v new value
     */
    public void setEmail(String v) 
    {
    
                  if (!ObjectUtils.equals(this.email, v))
              {
            this.email = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Birthday
     *
     * @return Date
     */
    public Date getBirthday()
    {
        return birthday;
    }

                        
    /**
     * Set the value of Birthday
     *
     * @param v new value
     */
    public void setBirthday(Date v) 
    {
    
                  if (!ObjectUtils.equals(this.birthday, v))
              {
            this.birthday = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Description
     *
     * @return String
     */
    public String getDescription()
    {
        return description;
    }

                        
    /**
     * Set the value of Description
     *
     * @param v new value
     */
    public void setDescription(String v) 
    {
    
                  if (!ObjectUtils.equals(this.description, v))
              {
            this.description = v;
            setModified(true);
        }
    
          
              }
  
         
                                
            
    /**
     * Collection to store aggregation of collAddresss
     */
    protected List collAddresss;

    /**
     * Temporary storage of collAddresss to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initAddresss()
    {
        if (collAddresss == null)
        {
            collAddresss = new ArrayList();
        }
    }

    /**
     * Method called to associate a Address object to this object
     * through the Address foreign key attribute
     *
     * @param l Address
     * @throws TorqueException
     */
    public void addAddress(Address l) throws TorqueException
    {
        getAddresss().add(l);
        l.setUser((User) this);
    }

    /**
     * The criteria used to select the current contents of collAddresss
     */
    private Criteria lastAddresssCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAddresss(new Criteria())
     *
     * @throws TorqueException
     */
    public List getAddresss() throws TorqueException
    {
        if (collAddresss == null)
        {
            collAddresss = getAddresss(new Criteria(10));
        }
        return collAddresss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this User has previously
     * been saved, it will retrieve related Addresss from storage.
     * If this User is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getAddresss(Criteria criteria) throws TorqueException
    {
        if (collAddresss == null)
        {
            if (isNew())
            {
               collAddresss = new ArrayList();
            }
            else
            {
                      criteria.add(AddressPeer.USER_ID, getId() );
                      collAddresss = AddressPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                      criteria.add(AddressPeer.USER_ID, getId());
                      if (!lastAddresssCriteria.equals(criteria))
                {
                    collAddresss = AddressPeer.doSelect(criteria);
                }
            }
        }
        lastAddresssCriteria = criteria;

        return collAddresss;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getAddresss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getAddresss(Connection con) throws TorqueException
    {
        if (collAddresss == null)
        {
            collAddresss = getAddresss(new Criteria(10), con);
        }
        return collAddresss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this User has previously
     * been saved, it will retrieve related Addresss from storage.
     * If this User is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getAddresss(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collAddresss == null)
        {
            if (isNew())
            {
               collAddresss = new ArrayList();
            }
            else
            {
                       criteria.add(AddressPeer.USER_ID, getId());
                       collAddresss = AddressPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                       criteria.add(AddressPeer.USER_ID, getId());
                       if (!lastAddresssCriteria.equals(criteria))
                 {
                     collAddresss = AddressPeer.doSelect(criteria, con);
                 }
             }
         }
         lastAddresssCriteria = criteria;

         return collAddresss;
     }

                  
              
                    
                              
                                
                                                              
                                        
                    
                    
          
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this User is new, it will return
     * an empty collection; or if this User has previously
     * been saved, it will retrieve related Addresss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in User.
     */
    protected List getAddresssJoinUser(Criteria criteria)
        throws TorqueException
    {
        if (collAddresss == null)
        {
            if (isNew())
            {
               collAddresss = new ArrayList();
            }
            else
            {
                            criteria.add(AddressPeer.USER_ID, getId());
                            collAddresss = AddressPeer.doSelectJoinUser(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                        criteria.add(AddressPeer.USER_ID, getId());
                        if (!lastAddresssCriteria.equals(criteria))
            {
                collAddresss = AddressPeer.doSelectJoinUser(criteria);
            }
        }
        lastAddresssCriteria = criteria;

        return collAddresss;
    }
                            


          
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(UserPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    UserPeer.doInsert((User) this, con);
                    setNew(false);
                }
                else
                {
                    UserPeer.doUpdate((User) this, con);
                }
            }

                                      
                
            if (collAddresss != null)
            {
                for (int i = 0; i < collAddresss.size(); i++)
                {
                    ((Address) collAddresss.get(i)).save(con);
                }
            }
                          alreadyInSave = false;
        }
      }


                          
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
            setId(((NumberKey) key).longValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
            setId(Long.parseLong(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public User copy() throws TorqueException
    {
        return copyInto(new User());
    }
  
    protected User copyInto(User copyObj) throws TorqueException
    {
          copyObj.setId(id);
          copyObj.setUserName(userName);
          copyObj.setEmail(email);
          copyObj.setBirthday(birthday);
          copyObj.setDescription(description);
  
                    copyObj.setId((long) 0);
                                    
                                      
                
        List v = getAddresss();
        for (int i = 0; i < v.size(); i++)
        {
            Address obj = (Address) v.get(i);
            copyObj.addAddress(obj.copy());
        }
                    
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UserPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("User:\n");
        str.append("Id = ")
           .append(getId())
           .append("\n");
        str.append("UserName = ")
           .append(getUserName())
           .append("\n");
        str.append("Email = ")
           .append(getEmail())
           .append("\n");
        str.append("Birthday = ")
           .append(getBirthday())
           .append("\n");
        str.append("Description = ")
           .append(getDescription())
           .append("\n");
        return(str.toString());
    }
}
